<!--
Copyright (C) 2026 Hyprism Launcher
SPDX-License-Identifier: GPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Hyprism.LocalNode</AssemblyName>
    <RootNamespace>Hyprism.LocalNode</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Hyprism.Core/Hyprism.Core.csproj" />
  </ItemGroup>

</Project>
